-- Esquema principal hibrido de Habitik para PostgreSQL.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.families (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre VARCHAR(100) NOT NULL,
    family_code VARCHAR(100) UNIQUE,
    meta_luz INTEGER DEFAULT 0,
    meta_agua INTEGER DEFAULT 0,
    avatar JSONB DEFAULT '{"url": null, "color": "#2e7d32", "emoji": "home"}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    avatar JSONB DEFAULT '{"letra": "U", "color": "#2e7d32", "url": null}'::jsonb,
    rol VARCHAR(50) DEFAULT 'miembro',
    family_id UUID REFERENCES public.families(id) ON DELETE SET NULL,
    xp INTEGER DEFAULT 0,
    nivel INTEGER DEFAULT 1,
    monedas INTEGER DEFAULT 0,
    trivia_correct_count INTEGER DEFAULT 0,
    trivia_last_updated VARCHAR(100),
    daily_bonus_claimed_at VARCHAR(100),
    onboarding_answers JSONB DEFAULT '{}'::jsonb,
    ultima_actividad DATE,
    racha_dias INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.evidences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    family_id UUID NOT NULL REFERENCES public.families(id) ON DELETE CASCADE,
    accion VARCHAR(255) NOT NULL,
    descripcion TEXT,
    likes INTEGER DEFAULT 0,
    xp INTEGER DEFAULT 0,
    emoji VARCHAR(20) DEFAULT 'star',
    snapshot_usuario JSONB DEFAULT '{}'::jsonb,
    media JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id UUID NOT NULL REFERENCES public.families(id) ON DELETE CASCADE,
    tarea VARCHAR(255) NOT NULL,
    asignado_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    hecho BOOLEAN DEFAULT FALSE,
    xp INTEGER DEFAULT 0,
    tipo VARCHAR(50) DEFAULT 'general',
    config JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.bills (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id UUID NOT NULL REFERENCES public.families(id) ON DELETE CASCADE,
    tipo VARCHAR(50) NOT NULL,
    consumo NUMERIC(10,2) NOT NULL,
    monto NUMERIC(12,2) NOT NULL,
    periodo VARCHAR(50) NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    ocr_result JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.family_rewards (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    family_id UUID NOT NULL REFERENCES public.families(id) ON DELETE CASCADE,
    titulo VARCHAR(255) NOT NULL,
    descripcion TEXT,
    emoji VARCHAR(20) DEFAULT 'gift',
    costo INTEGER DEFAULT 100,
    disponible BOOLEAN DEFAULT TRUE,
    es_familiar BOOLEAN NOT NULL DEFAULT FALSE,
    creador_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    last_redeemed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.family_rewards
ADD COLUMN IF NOT EXISTS es_familiar BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS public.canjes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reward_id BIGINT NOT NULL REFERENCES public.family_rewards(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    family_id UUID NOT NULL REFERENCES public.families(id) ON DELETE CASCADE,
    costo_pagado INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.historial_gamificacion (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    origen_actividad VARCHAR(100) NOT NULL,
    monedas_otorgadas INTEGER DEFAULT 0,
    xp_otorgada INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.daily_bonus_claims (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    bonus_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, bonus_date)
);

CREATE TABLE IF NOT EXISTS public.reto_validations (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    family_id UUID NOT NULL REFERENCES public.families(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    reto VARCHAR(255) NOT NULL,
    hora VARCHAR(50) DEFAULT 'Recien',
    xp INTEGER DEFAULT 0,
    monedas INTEGER DEFAULT 0,
    evidencias JSONB DEFAULT '[]'::jsonb,
    snapshot_usuario JSONB DEFAULT '{}'::jsonb,
    requiere_evidencia BOOLEAN DEFAULT FALSE,
    estado VARCHAR(50) DEFAULT 'pendiente',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.achievements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    logro_key VARCHAR(100) NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    desbloqueado_en TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, logro_key)
);

CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    desc_text TEXT NOT NULL,
    visual JSONB DEFAULT '{"icon": "notifications", "color": "#388E3C"}'::jsonb,
    payload JSONB DEFAULT '{}'::jsonb,
    is_read BOOLEAN DEFAULT FALSE,
    family_id UUID REFERENCES public.families(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    sender_name VARCHAR(100),
    type VARCHAR(100) DEFAULT 'ALERTA_GENERAL',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.qr_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id UUID NOT NULL REFERENCES public.families(id) ON DELETE CASCADE,
    token VARCHAR(100) UNIQUE NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.shower_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    family_id UUID REFERENCES public.families(id) ON DELETE CASCADE,
    duracion_segundos INTEGER NOT NULL,
    estado VARCHAR(50) NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    xp_otorgada INTEGER DEFAULT 0,
    monedas_otorgadas INTEGER DEFAULT 0,
    es_valido BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.families
ADD COLUMN IF NOT EXISTS avatar JSONB DEFAULT '{"url": null, "color": "#2e7d32", "emoji": "home"}'::jsonb;

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS avatar JSONB DEFAULT '{"letra": "U", "color": "#2e7d32", "url": null}'::jsonb;

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS ultima_actividad DATE;

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS racha_dias INTEGER DEFAULT 0;

UPDATE public.profiles
SET avatar = jsonb_build_object(
    'letra', COALESCE(NULLIF(avatar->>'letra', ''), LEFT(nombre, 1), 'U'),
    'color', COALESCE(NULLIF(avatar->>'color', ''), '#2e7d32'),
    'url', avatar->'url'
)
WHERE avatar IS NULL OR avatar = '{}'::jsonb;

ALTER TABLE public.evidences
ADD COLUMN IF NOT EXISTS snapshot_usuario JSONB DEFAULT '{}'::jsonb;

ALTER TABLE public.evidences
ADD COLUMN IF NOT EXISTS media JSONB DEFAULT '[]'::jsonb;

ALTER TABLE public.tasks
ADD COLUMN IF NOT EXISTS config JSONB DEFAULT '{}'::jsonb;

ALTER TABLE public.bills
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;

ALTER TABLE public.bills
ADD COLUMN IF NOT EXISTS ocr_result JSONB DEFAULT '{}'::jsonb;

ALTER TABLE public.family_rewards
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;

ALTER TABLE public.family_rewards
ADD COLUMN IF NOT EXISTS es_familiar BOOLEAN NOT NULL DEFAULT FALSE;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'family_rewards'
          AND column_name = 'id'
          AND is_identity = 'NO'
          AND column_default IS NULL
    ) THEN
        CREATE SEQUENCE IF NOT EXISTS public.family_rewards_id_seq;
        ALTER SEQUENCE public.family_rewards_id_seq OWNED BY public.family_rewards.id;
        ALTER TABLE public.family_rewards ALTER COLUMN id SET DEFAULT nextval('public.family_rewards_id_seq');
        PERFORM setval(
            'public.family_rewards_id_seq',
            GREATEST(COALESCE((SELECT MAX(id) FROM public.family_rewards), 0), 1),
            true
        );
    END IF;
END $$;

ALTER TABLE public.reto_validations
ALTER COLUMN evidencias DROP DEFAULT;

ALTER TABLE public.reto_validations
ALTER COLUMN evidencias TYPE JSONB USING to_jsonb(evidencias);

ALTER TABLE public.reto_validations
ALTER COLUMN evidencias SET DEFAULT '[]'::jsonb;

ALTER TABLE public.reto_validations
ADD COLUMN IF NOT EXISTS snapshot_usuario JSONB DEFAULT '{}'::jsonb;

ALTER TABLE public.achievements
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;

ALTER TABLE public.notifications
ADD COLUMN IF NOT EXISTS visual JSONB DEFAULT '{"icon": "notifications", "color": "#388E3C"}'::jsonb;

ALTER TABLE public.notifications
ADD COLUMN IF NOT EXISTS payload JSONB DEFAULT '{}'::jsonb;

ALTER TABLE public.notifications
ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE public.notifications
ADD COLUMN IF NOT EXISTS family_id UUID REFERENCES public.families(id) ON DELETE CASCADE;

ALTER TABLE public.notifications
ADD COLUMN IF NOT EXISTS sender_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.notifications
ADD COLUMN IF NOT EXISTS sender_name VARCHAR(100);

ALTER TABLE public.notifications
ADD COLUMN IF NOT EXISTS type VARCHAR(100) DEFAULT 'ALERTA_GENERAL';

ALTER TABLE public.shower_logs
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;

ALTER TABLE public.shower_logs
ADD COLUMN IF NOT EXISTS family_id UUID REFERENCES public.families(id) ON DELETE CASCADE;

ALTER TABLE public.shower_logs
ADD COLUMN IF NOT EXISTS xp_otorgada INTEGER DEFAULT 0;

ALTER TABLE public.shower_logs
ADD COLUMN IF NOT EXISTS monedas_otorgadas INTEGER DEFAULT 0;

ALTER TABLE public.shower_logs
ADD COLUMN IF NOT EXISTS es_valido BOOLEAN DEFAULT TRUE;

CREATE INDEX IF NOT EXISTS idx_profiles_family ON public.profiles(family_id);
CREATE INDEX IF NOT EXISTS idx_evidences_family ON public.evidences(family_id);
CREATE INDEX IF NOT EXISTS idx_tasks_family ON public.tasks(family_id);
CREATE INDEX IF NOT EXISTS idx_bills_family ON public.bills(family_id);
CREATE INDEX IF NOT EXISTS idx_family_rewards_family ON public.family_rewards(family_id);
CREATE INDEX IF NOT EXISTS idx_canjes_user_reward ON public.canjes(user_id, reward_id, created_at);
CREATE INDEX IF NOT EXISTS idx_canjes_family_reward ON public.canjes(family_id, reward_id, created_at);
CREATE INDEX IF NOT EXISTS idx_historial_gamificacion_user_day ON public.historial_gamificacion(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_daily_bonus_claims_user_date ON public.daily_bonus_claims(user_id, bonus_date);
CREATE INDEX IF NOT EXISTS idx_reto_validations_family_estado ON public.reto_validations(family_id, estado);
CREATE INDEX IF NOT EXISTS idx_achievements_user ON public.achievements(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_qr_tokens_token ON public.qr_tokens(token);
CREATE INDEX IF NOT EXISTS idx_shower_logs_user ON public.shower_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_families_avatar_gin ON public.families USING GIN (avatar);
CREATE INDEX IF NOT EXISTS idx_profiles_avatar_gin ON public.profiles USING GIN (avatar);
CREATE INDEX IF NOT EXISTS idx_profiles_onboarding_answers_gin ON public.profiles USING GIN (onboarding_answers);
CREATE INDEX IF NOT EXISTS idx_tasks_config_gin ON public.tasks USING GIN (config);
CREATE INDEX IF NOT EXISTS idx_bills_metadata_gin ON public.bills USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_bills_ocr_result_gin ON public.bills USING GIN (ocr_result);
CREATE INDEX IF NOT EXISTS idx_evidences_media_gin ON public.evidences USING GIN (media);
CREATE INDEX IF NOT EXISTS idx_family_rewards_metadata_gin ON public.family_rewards USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_reto_validations_evidencias_gin ON public.reto_validations USING GIN (evidencias);
CREATE INDEX IF NOT EXISTS idx_notifications_payload_gin ON public.notifications USING GIN (payload);
